export const products = [
  {
    id: '1',
    name: 'Bay Leaves',
    description: 'Luxurious, hand-harvested bay leaves with an intense aroma and rich color. Perfect for paella, risotto, and Middle Eastern cuisine.',
    price: 9.6,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=400&q=80',
    category: 'Herb',
    origin: 'Turkey',
    usage: 'Add whole to soups, stews, and sauces. Remove before serving.',
    conditions: 'Store in a cool, dry place away from sunlight.',
    expiration: '2 years from packaging',
  },
  {
    id: '2',
    name: 'Saffron',
    description: 'Premium saffron threads, hand-picked for the best flavor and color.',
    price: 24.0,
    image: 'https://images.unsplash.com/photo-1464306076886-debca5e8a6b0?auto=format&fit=crop&w=400&q=80',
    category: 'Flower',
    origin: 'Iran',
    usage: 'Steep in warm water or milk before adding to dishes like paella or risotto.',
    conditions: 'Keep in an airtight container, away from moisture.',
    expiration: '3 years from packaging',
  },
  {
    id: '3',
    name: 'Cinnamon Sticks',
    description: 'Aromatic cinnamon sticks, perfect for desserts and drinks.',
    price: 5.5,
    image: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80',
    category: 'Bark',
    origin: 'Sri Lanka',
    usage: 'Simmer in liquids for flavor or grate into baked goods.',
    conditions: 'Store in a sealed jar in a dry place.',
    expiration: '2 years from packaging',
  },
  {
    id: '4',
    name: 'Black Pepper',
    description: 'Whole black peppercorns with a bold, pungent flavor.',
    price: 4.2,
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
    category: 'Seed',
    origin: 'India',
    usage: 'Grind fresh over dishes for best flavor.',
    conditions: 'Keep in a dry, airtight container.',
    expiration: '3 years from packaging',
  },
  {
    id: '5',
    name: 'Star Anise',
    description: 'Star-shaped spice with a sweet, licorice-like flavor. Great for stews and desserts.',
    price: 7.0,
    image: 'https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=400&q=80',
    category: 'Fruit',
    origin: 'China',
    usage: 'Add whole to broths, teas, and braises.',
    conditions: 'Store in a cool, dry place.',
    expiration: '2 years from packaging',
  },
  {
    id: '6',
    name: 'Cloves',
    description: 'Intensely aromatic dried flower buds, used in both sweet and savory dishes.',
    price: 6.5,
    image: 'https://images.unsplash.com/photo-1519864600265-abb23847ef2c?auto=format&fit=crop&w=400&q=80',
    category: 'Flower',
    origin: 'Madagascar',
    usage: 'Use whole in stews or ground in baking.',
    conditions: 'Keep in a sealed container away from heat.',
    expiration: '2 years from packaging',
  },
  {
    id: '7',
    name: 'Cumin Seeds',
    description: 'Earthy, nutty seeds essential in many world cuisines.',
    price: 3.8,
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
    category: 'Seed',
    origin: 'Egypt',
    usage: 'Toast before grinding for enhanced flavor.',
    conditions: 'Store in a dry, airtight jar.',
    expiration: '2 years from packaging',
  },
  {
    id: '8',
    name: 'Turmeric',
    description: 'Bright yellow spice with a warm, bitter flavor. Used for color and health benefits.',
    price: 4.0,
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
    category: 'Root',
    origin: 'India',
    usage: 'Add to curries, rice, and smoothies.',
    conditions: 'Keep in a cool, dry place.',
    expiration: '3 years from packaging',
  },
  {
    id: '9',
    name: 'Cardamom',
    description: 'Sweet, floral spice used in chai, desserts, and savory dishes.',
    price: 12.0,
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
    category: 'Seed',
    origin: 'Guatemala',
    usage: 'Crush pods to release seeds for maximum flavor.',
    conditions: 'Store in a sealed container away from light.',
    expiration: '2 years from packaging',
  },
  {
    id: '10',
    name: 'Nutmeg',
    description: 'Warm, nutty spice grated into sweet and savory recipes.',
    price: 8.0,
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
    category: 'Seed',
    origin: 'Indonesia',
    usage: 'Grate fresh into desserts, sauces, and drinks.',
    conditions: 'Keep whole nutmeg in a dry, airtight jar.',
    expiration: '2 years from packaging',
  },
  {
    id: '11',
    name: 'Paprika',
    description: 'Ground red pepper with a sweet, smoky flavor. Essential in Hungarian cuisine.',
    price: 3.5,
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
    category: 'Fruit',
    origin: 'Hungary',
    usage: 'Sprinkle on eggs, stews, and roasted vegetables.',
    conditions: 'Store in a cool, dark place.',
    expiration: '1 year from packaging',
  },
  {
    id: '12',
    name: 'Sumac',
    description: 'Tangy, lemony spice popular in Middle Eastern cooking.',
    price: 5.0,
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
    category: 'Berry',
    origin: 'Turkey',
    usage: 'Sprinkle on salads, meats, and dips.',
    conditions: 'Keep in a sealed jar away from moisture.',
    expiration: '2 years from packaging',
  },
  {
    id: '13',
    name: 'Fennel Seeds',
    description: 'Sweet, anise-flavored seeds used in sausages and breads.',
    price: 3.2,
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
    category: 'Seed',
    origin: 'India',
    usage: 'Use in breads, teas, and spice blends.',
    conditions: 'Store in a dry, airtight container.',
    expiration: '2 years from packaging',
  },
  {
    id: '14',
    name: 'Mustard Seeds',
    description: 'Tiny, pungent seeds used for pickling and curries.',
    price: 2.8,
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
    category: 'Seed',
    origin: 'Canada',
    usage: 'Crack or toast before adding to dishes.',
    conditions: 'Keep in a sealed jar in a cool place.',
    expiration: '2 years from packaging',
  },
  {
    id: '15',
    name: 'Coriander',
    description: 'Citrusy, nutty seeds used in spice blends and curries.',
    price: 3.0,
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=400&q=80',
    category: 'Seed',
    origin: 'Morocco',
    usage: 'Toast and grind for curries and spice blends.',
    conditions: 'Store in a dry, airtight container.',
    expiration: '2 years from packaging',
  },
]; 